[package]
name = "afxdp"
description = "AF XDP for Rust"
repository = "https://github.com/aterlo/afxdp-rs"
homepage = "https://github.com/aterlo/afxdp-rs"
version = "0.1.0"
authors = ["Dan Siemon <dan@aterlo.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
libbpf-sys = { version = "0.0.6-4" }
libc = "*"
errno = "*"
arraydeque = "0.4"
crossbeam-channel = "0.4"
rlimit = "0.3"
structopt = "0.3"
