[package]
name = "afxdp"
description = "AF XDP for Rust"
repository = "https://github.com/aterlo/afxdp-rs"
homepage = "https://github.com/aterlo/afxdp-rs"
version = "0.1.2"
authors = ["Dan Siemon <dan@aterlo.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["AF_XDP", "XDP"]
categories = ["network-programming"]
readme = "README.md"
maintenance = { status = "actively-developed" }

[dependencies]
libbpf-sys = { version = "0.0.7-1" }
libc = "0.2"
errno = "0.2"
arraydeque = "0.4"
crossbeam-channel = "0.4"
rlimit = "0.3"
structopt = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bufpool"
harness = false
